import Navbar from "@/components/features/Navbar";
import { AuthProvider } from "@/hooks/use-auth";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.app",
  applicationName: "Create Next App",
  authors: [{ name: "Your Name", url: "https://your-website.com" }],
  keywords: ["Next.js", "React", "TypeScript"],
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://your-app-url.com",
    siteName: "Create Next App",
    images: [
      {
        url: "https://your-app-url.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Og Image Alt",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`font-sans ${GeistSans.variable} ${GeistMono.variable}`}>
        <LanguageProvider>
          <Suspense fallback={<Loading />}>
            <QueryProvider>
              <Toaster
                richColors
                position="top-center"
                toastOptions={{
                  className: "mx-auto",
                }}
              />
              <AuthProvider>
                <Navbar />
                {children}
              </AuthProvider>
            </QueryProvider>
          </Suspense>
          {/* </ThemeProvider> */}
        </LanguageProvider>
        <Analytics />
      </body>
    </html>
  );
}
